### ISSUE TITLE
Benchmark results not available at the website

### ISSUE THREAD

**Issue by lucianor** [TheRemote/PiBenchmarks#29] opened 2023-07-27 15:47 UTC
Hello. I ran the benchmark scripts on my new Orange Pi 5 board, and those results got published in the site without a problem: https://pibenchmarks.com/user/lucianor/

However, I ran the benchmark script a couple of minutes after on my Raspberry Pi 4b (which is being replaced by the new board) but no results have been posted on the site: can't find them in 'Latest' or in my username page - I also tried anonymous posting.

1) Is there a rate limit of how many results one can post in a day? 
2) Is there a delay for the website to update? I found the OPI5 result after a couple of minutes
3) Is there a filter on more popular boards results which could justify RPI4b results not being published?

Thank you

**Comment by terrorpup** [comment] 2023-07-29 02:24
I have a similar issue with the Radxa Rock 5A and Indiedroid-Nova, and I am trying to get eMMC for the Orange Pi to show up.

**Comment by rmkilc** [comment] 2023-11-07 03:03
When I run it on my Orange Pi 5 Plus with a Samsung 970 EVO Plus NVMe M.2 SSD running Armbian, the results do not show up on the website. I do not get the "Result submitted successfully" line. The only thing that stands out to me is this part but I'm not sure if it's related:

```
Running additional hardware identification tests...
bash: line 398: warning: command substitution: ignored null byte in input
```

**Comment by rglidden** [comment] 2023-11-14 01:23
The error appears to be caused by a bug in the `nvme` command an recent kernel changes in newer Linux versions. See my https://github.com/TheRemote/PiBenchmarks/issues/31#issuecomment-1809390604 for a temporary work around.

**Comment by TheRemote** [comment] 2023-11-26 20:05
This should now be fixed in the latest version!

**Closed by TheRemote** 2023-11-26 20:05 UTC
